sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - DEPS=lowest
    - php: 5.5
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
    - php: 7
    - php: 7
      env:
        - DEPS=lowest
    - php: hhvm
    - php: hhvm
      env:
        - DEPS=lowest

before_script:
  - composer self-update
  - phpenv config-rm xdebug.ini
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction ; fi
  - travis_retry composer install --no-interaction

script:
  - composer test

matrix:
  fast_finish: true
