language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

env:
  - DEPS=lowest
  - DEPS=latest

before_script:
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --no-interaction ; fi

script:
  - composer test

matrix:
  fast_finish: true
