language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.4

env:
  - DEPS=lowest
  - DEPS=latest

before_script:
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --no-interaction ; fi

script:
  - composer test

matrix:
  fast_finish: true
