language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - phpunit

matrix:
  fast_finish: true
